"""
FEMM 4.2 Lua script generator for electrostatic electrode simulations.

Generates a Lua script that FEMM can execute to build electrode geometry,
assign materials and boundary conditions, and optionally solve the problem.
Model building is delegated to ``FEMMModelBuilder`` with the ``LuaBackend``.
"""

from datetime import datetime
from typing import List, Tuple, Dict, Any

from simulation.femm_model import LuaBackend, FEMMModelBuilder


class FEMMExporter:
    """Generates FEMM 4.2 electrostatic Lua scripts from electrode geometry."""

    def generate_script(self, curves: List[Tuple[List[float], List[float], str]],
                        config: Dict[str, Any]) -> str:
        """
        Generate a complete FEMM electrostatic Lua script.

        Args:
            curves: list of (x_coords, y_coords, label) tuples.
            config: simulation parameters (problem_type, units, depth,
                    voltage_top, voltage_bottom, permittivity, mesh_size,
                    auto_solve).

        Returns:
            Complete Lua script as a string.
        """
        lines = self._header()

        # Build model via shared builder
        backend = LuaBackend()
        builder = FEMMModelBuilder(backend)
        builder.build(curves, config)
        lines.extend(backend.lines)

        # Finalize (save / solve / post-processing)
        lines.extend(self._finalize(config, curves))

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _header(self):
        stamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return [
            "-- FEMM 4.2 Electrostatic Simulation",
            f"-- Generated by Electrode Profile Generator on {stamp}",
            "",
        ]

    def _finalize(self, config, curves=None):
        lines = []
        if config.get("auto_solve", False):
            save_path = config.get("save_path", "")
            if save_path:
                lines += [
                    "-- Save",
                    f'ei_saveas("{save_path}")',
                    "",
                ]
            lines += [
                "-- Solve",
                "ei_analyze()",
                "ei_loadsolution()",
                "",
            ]
            if curves:
                lines += self._post_processing(curves, config)
        return lines

    def _post_processing(self, curves, config):
        """Generate Lua commands to select top electrode contour and plot |E|."""
        from core.contour import build_top_contour

        lines = ["-- Post-processing: Electric field along top electrode"]
        lines.append("eo_clearcontour()")

        pts = build_top_contour(curves)

        for x, y in pts:
            lines.append(f"eo_addcontour({x:.6f}, {y:.6f})")

        lines.append("")
        lines.append("-- Plot |E| along top electrode contour (FEMM plot window)")
        lines.append("eo_makeplot(4, 500)")
        lines.append("")

        return lines
