"""
FEMM 4.2 Lua script generator for electrostatic electrode simulations.

Generates a Lua script that FEMM can execute to build electrode geometry,
assign materials and boundary conditions, and optionally solve the problem.
"""

from datetime import datetime
from typing import List, Tuple, Dict, Any


class FEMMExporter:
    """Generates FEMM 4.2 electrostatic Lua scripts from electrode geometry."""

    def generate_script(self, curves: List[Tuple[List[float], List[float], str]],
                        config: Dict[str, Any]) -> str:
        """
        Generate a complete FEMM electrostatic Lua script.

        Args:
            curves: list of (x_coords, y_coords, label) tuples.
                    Labels containing 'Top' receive the top electrode voltage;
                    labels containing 'Bot' receive the bottom electrode voltage.
            config: simulation parameters:
                problem_type   - 'planar' or 'axi'
                units          - 'millimeters', 'centimeters', etc.
                depth          - depth for planar problems (float)
                voltage_top    - top electrode voltage (V)
                voltage_bottom - bottom electrode voltage (V)
                permittivity   - relative permittivity of gap medium
                mesh_size      - element size (0 = auto)
                auto_solve     - run analysis automatically (bool)

        Returns:
            Complete Lua script as a string.
        """
        lines = []
        lines += self._header()
        lines += self._problem_setup(config)
        lines += self._materials(config)
        lines += self._boundary_props(config)
        lines += self._electrode_geometry(curves, config)
        lines += self._outer_boundary(curves, config)
        lines += self._block_labels(curves, config)
        lines += self._finalize(config)
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Private helpers — each emits a section of the Lua script
    # ------------------------------------------------------------------

    def _header(self):
        stamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return [
            "-- FEMM 4.2 Electrostatic Simulation",
            f"-- Generated by Electrode Profile Generator on {stamp}",
            "",
        ]

    def _problem_setup(self, config):
        prob = config.get("problem_type", "planar")
        units = config.get("units", "millimeters")
        depth = config.get("depth", 1.0)
        return [
            "-- Problem definition",
            "newdocument(1)",
            f'ei_probdef("{units}", "{prob}", 1e-8, {depth}, 30)',
            "",
        ]

    def _materials(self, config):
        eps = config.get("permittivity", 1.0)
        return [
            "-- Materials",
            f'ei_addmaterial("Dielectric", {eps}, {eps}, 0)',
            "",
        ]

    def _boundary_props(self, config):
        v_top = config.get("voltage_top", 1000.0)
        v_bot = config.get("voltage_bottom", 0.0)
        return [
            "-- Boundary conditions",
            f'ei_addboundprop("TopElectrode", {v_top}, 0, 0, 0, 0)',
            f'ei_addboundprop("BotElectrode", {v_bot}, 0, 0, 0, 0)',
            'ei_addboundprop("Outer", 0, 0, 0, 0, 1)',
            "",
        ]

    def _electrode_geometry(self, curves, config):
        mesh = config.get("mesh_size", 0)
        automesh = 1 if mesh == 0 else 0

        lines = ["-- Electrode geometry"]
        top_mids = []
        bot_mids = []

        for cx, cy, label in curves:
            points = list(zip(cx, cy))
            lines.append(f"-- {label}")

            # Add nodes
            for x, y in points:
                lines.append(f"ei_addnode({x:.6f}, {y:.6f})")

            # Add segments and collect midpoints for boundary assignment
            for i in range(len(points) - 1):
                x1, y1 = points[i]
                x2, y2 = points[i + 1]
                lines.append(f"ei_addsegment({x1:.6f}, {y1:.6f}, {x2:.6f}, {y2:.6f})")
                mid = ((x1 + x2) / 2, (y1 + y2) / 2)
                if "Bot" in label:
                    bot_mids.append(mid)
                else:
                    top_mids.append(mid)

        lines.append("")

        # Batch-select and assign top electrode boundary
        lines.append("-- Assign top electrode boundary")
        for mx, my in top_mids:
            lines.append(f"ei_selectsegment({mx:.6f}, {my:.6f})")
        lines.append(f'ei_setsegmentprop("TopElectrode", {mesh}, {automesh}, 0, 1)')
        lines.append("ei_clearselected()")
        lines.append("")

        # Batch-select and assign bottom electrode boundary
        lines.append("-- Assign bottom electrode boundary")
        for mx, my in bot_mids:
            lines.append(f"ei_selectsegment({mx:.6f}, {my:.6f})")
        lines.append(f'ei_setsegmentprop("BotElectrode", {mesh}, {automesh}, 0, 2)')
        lines.append("ei_clearselected()")
        lines.append("")

        return lines

    def _outer_boundary(self, curves, config):
        is_axi = config.get("problem_type") == "axi"
        mesh = config.get("mesh_size", 0)
        automesh = 1 if mesh == 0 else 0

        all_x = [x for cx, _, _ in curves for x in cx]
        all_y = [y for _, cy, _ in curves for y in cy]

        x_max = max(all_x)
        y_min, y_max = min(all_y), max(all_y)

        span = max(x_max - min(all_x), y_max - y_min)
        pad = span * 0.5

        bx0 = 0 if is_axi else min(all_x) - pad
        bx1 = x_max + pad
        by0 = y_min - pad
        by1 = y_max + pad

        corners = [(bx0, by0), (bx1, by0), (bx1, by1), (bx0, by1)]

        lines = ["-- Outer boundary"]
        for x, y in corners:
            lines.append(f"ei_addnode({x:.6f}, {y:.6f})")

        outer_mids = []
        for i in range(4):
            x1, y1 = corners[i]
            x2, y2 = corners[(i + 1) % 4]
            lines.append(f"ei_addsegment({x1:.6f}, {y1:.6f}, {x2:.6f}, {y2:.6f})")
            # Skip axis segments (r=0) in axisymmetric mode — FEMM handles those
            on_axis = is_axi and abs(x1) < 1e-10 and abs(x2) < 1e-10
            if not on_axis:
                outer_mids.append(((x1 + x2) / 2, (y1 + y2) / 2))

        lines.append("")
        lines.append("-- Assign outer boundary")
        for mx, my in outer_mids:
            lines.append(f"ei_selectsegment({mx:.6f}, {my:.6f})")
        lines.append(f'ei_setsegmentprop("Outer", {mesh}, {automesh}, 0, 3)')
        lines.append("ei_clearselected()")
        lines.append("")

        return lines

    def _block_labels(self, curves, config):
        mesh = config.get("mesh_size", 0)
        automesh = 1 if mesh == 0 else 0
        is_axi = config.get("problem_type") == "axi"

        # Place label in the gap between electrodes
        if is_axi:
            all_x = [x for cx, _, _ in curves for x in cx]
            label_x = max(all_x) * 0.25
        else:
            label_x = 0

        return [
            "-- Dielectric region",
            f"ei_addblocklabel({label_x:.6f}, 0)",
            f"ei_selectlabel({label_x:.6f}, 0)",
            f'ei_setblockprop("Dielectric", {automesh}, {mesh}, 0)',
            "ei_clearselected()",
            "",
        ]

    def _finalize(self, config):
        lines = ["ei_zoomnatural()", ""]
        if config.get("auto_solve", False):
            lines += [
                "-- Solve",
                "ei_analyze()",
                "ei_loadsolution()",
                "",
            ]
        return lines
